name: GitHub Actions Demo  
run-name: Testing out GitHub Actions 
on: [push]  
jobs: 
Basic-Workflow:  
runs-on: ubuntu-latest  
steps: 
- name: Run a one-line script
run: echo "Job is executing as part of Basic workflow"
